### ISSUE TITLE
[Bug]: MergeError: conflicting values for variable 'lon_bnds' on objects to be combined. You can skip this check by specifying compat='override'.

### ISSUE THREAD

**Issue by bonfils2** [xCDAT/xcdat#470] opened 2023-05-08 08:21 UTC
### What happened?

I can't open a specific piControl run due to a merger issue for lo_bnds

### What did you expect to happen?

I expected to open the file(s). i tried "override" but did not work. i am not sure how to use override.

### Minimal Complete Verifiable Example

```python
filq='/p/css03/esgf_publish/CMIP6/CMIP/NCC/NorESM2-LM/piControl/r1i1p1f1/Amon/tas/gn/v20210118/*.nc'
ds=xc.open_mfdataset(filq,decode_times=True,add_bounds=True)
```

### Relevant log output

```python
Merger error
File ~/my_envs/xcdatonly/lib/python3.10/site-packages/xcdat/dataset.py:216, in open_mfdataset(paths, data_var, add_bounds, decode_times, center_times, lon_orient, data_vars, preprocess, **kwargs)
    212         paths = _parse_dir_for_nc_glob(paths)  # type: ignore
    214 preprocess = partial(_preprocess, decode_times=decode_times, callable=preprocess)
--> 216 ds = xr.open_mfdataset(
    217     paths,
    218     decode_times=False,
    219     data_vars=data_vars,
    220     preprocess=preprocess,
    221     **kwargs,  # type: ignore
    222 )
    224 ds = _postprocess_dataset(ds, data_var, center_times, add_bounds, lon_orient)
    226 return ds

File ~/my_envs/xcdatonly/lib/python3.10/site-packages/xarray/backends/api.py:1011, in open_mfdataset(paths, chunks, concat_dim, compat, preprocess, engine, data_vars, coords, combine, parallel, join, attrs_file, combine_attrs, **kwargs)
    998     combined = _nested_combine(
    999         datasets,
   1000         concat_dims=concat_dim,
   (...)
   1006         combine_attrs=combine_attrs,
   1007     )
   1008 elif combine == "by_coords":
   1009     # Redo ordering from coordinates, ignoring how they were ordered
   1010     # previously
-> 1011     combined = combine_by_coords(
   1012         datasets,
   1013         compat=compat,
   1014         data_vars=data_vars,
   1015         coords=coords,
   1016         join=join,
   1017         combine_attrs=combine_attrs,
   1018     )
   1019 else:
   1020     raise ValueError(
   1021         "{} is an invalid option for the keyword argument"
   1022         " ``combine``".format(combine)
   1023     )

File ~/my_envs/xcdatonly/lib/python3.10/site-packages/xarray/core/combine.py:976, in combine_by_coords(data_objects, compat, data_vars, coords, fill_value, join, combine_attrs, datasets)
    974     concatenated_grouped_by_data_vars = []
    975     for vars, datasets_with_same_vars in grouped_by_vars:
--> 976         concatenated = _combine_single_variable_hypercube(
    977             list(datasets_with_same_vars),
    978             fill_value=fill_value,
    979             data_vars=data_vars,
    980             coords=coords,
    981             compat=compat,
    982             join=join,
    983             combine_attrs=combine_attrs,
    984         )
    985         concatenated_grouped_by_data_vars.append(concatenated)
    987 return merge(
    988     concatenated_grouped_by_data_vars,
    989     compat=compat,
   (...)
    992     combine_attrs=combine_attrs,
    993 )

File ~/my_envs/xcdatonly/lib/python3.10/site-packages/xarray/core/combine.py:634, in _combine_single_variable_hypercube(datasets, fill_value, data_vars, coords, compat, join, combine_attrs)
    631     _check_dimension_depth_tile_ids(combined_ids)
    633 # Concatenate along all of concat_dims one by one to create single ds
--> 634 concatenated = _combine_nd(
    635     combined_ids,
    636     concat_dims=concat_dims,
    637     data_vars=data_vars,
    638     coords=coords,
    639     compat=compat,
    640     fill_value=fill_value,
    641     join=join,
    642     combine_attrs=combine_attrs,
    643 )
    645 # Check the overall coordinates are monotonically increasing
    646 for dim in concat_dims:

File ~/my_envs/xcdatonly/lib/python3.10/site-packages/xarray/core/combine.py:235, in _combine_nd(combined_ids, concat_dims, data_vars, coords, compat, fill_value, join, combine_attrs)
    231 # Each iteration of this loop reduces the length of the tile_ids tuples
    232 # by one. It always combines along the first dimension, removing the first
    233 # element of the tuple
    234 for concat_dim in concat_dims:
--> 235     combined_ids = _combine_all_along_first_dim(
    236         combined_ids,
    237         dim=concat_dim,
    238         data_vars=data_vars,
    239         coords=coords,
    240         compat=compat,
    241         fill_value=fill_value,
    242         join=join,
    243         combine_attrs=combine_attrs,
    244     )
    245 (combined_ds,) = combined_ids.values()
    246 return combined_ds

File ~/my_envs/xcdatonly/lib/python3.10/site-packages/xarray/core/combine.py:270, in _combine_all_along_first_dim(combined_ids, dim, data_vars, coords, compat, fill_value, join, combine_attrs)
    268     combined_ids = dict(sorted(group))
    269     datasets = combined_ids.values()
--> 270     new_combined_ids[new_id] = _combine_1d(
    271         datasets, dim, compat, data_vars, coords, fill_value, join, combine_attrs
    272     )
    273 return new_combined_ids

File ~/my_envs/xcdatonly/lib/python3.10/site-packages/xarray/core/combine.py:293, in _combine_1d(datasets, concat_dim, compat, data_vars, coords, fill_value, join, combine_attrs)
    291 if concat_dim is not None:
    292     try:
--> 293         combined = concat(
    294             datasets,
    295             dim=concat_dim,
    296             data_vars=data_vars,
    297             coords=coords,
    298             compat=compat,
    299             fill_value=fill_value,
    300             join=join,
    301             combine_attrs=combine_attrs,
    302         )
    303     except ValueError as err:
    304         if "encountered unexpected variable" in str(err):

File ~/my_envs/xcdatonly/lib/python3.10/site-packages/xarray/core/concat.py:249, in concat(objs, dim, data_vars, coords, compat, positions, fill_value, join, combine_attrs)
    237     return _dataarray_concat(
    238         objs,
    239         dim=dim,
   (...)
    246         combine_attrs=combine_attrs,
    247     )
    248 elif isinstance(first_obj, Dataset):
--> 249     return _dataset_concat(
    250         objs,
    251         dim=dim,
    252         data_vars=data_vars,
    253         coords=coords,
    254         compat=compat,
    255         positions=positions,
    256         fill_value=fill_value,
    257         join=join,
    258         combine_attrs=combine_attrs,
    259     )
    260 else:
    261     raise TypeError(
    262         "can only concatenate xarray Dataset and DataArray "
    263         f"objects, got {type(first_obj)}"
    264     )

File ~/my_envs/xcdatonly/lib/python3.10/site-packages/xarray/core/concat.py:521, in _dataset_concat(datasets, dim, data_vars, coords, compat, positions, fill_value, join, combine_attrs)
    515 if variables_to_merge:
    516     grouped = {
    517         k: v
    518         for k, v in collect_variables_and_indexes(list(datasets)).items()
    519         if k in variables_to_merge
    520     }
--> 521     merged_vars, merged_indexes = merge_collected(
    522         grouped, compat=compat, equals=equals
    523     )
    524     result_vars.update(merged_vars)
    525     result_indexes.update(merged_indexes)

File ~/my_envs/xcdatonly/lib/python3.10/site-packages/xarray/core/merge.py:291, in merge_collected(grouped, prioritized, compat, combine_attrs, equals)
    289 variables = [variable for variable, _ in elements_list]
    290 try:
--> 291     merged_vars[name] = unique_variable(
    292         name, variables, compat, equals.get(name, None)
    293     )
    294 except MergeError:
    295     if compat != "minimal":
    296         # we need more than "minimal" compatibility (for which
    297         # we drop conflicting coordinates)

File ~/my_envs/xcdatonly/lib/python3.10/site-packages/xarray/core/merge.py:145, in unique_variable(name, variables, compat, equals)
    142                 break
    144 if not equals:
--> 145     raise MergeError(
    146         f"conflicting values for variable {name!r} on objects to be combined. "
    147         "You can skip this check by specifying compat='override'."
    148     )
    150 if combine_method:
    151     for var in variables[1:]:

MergeError: conflicting values for variable 'lon_bnds' on objects to be combined. You can skip this check by specifying compat='override'.
```

### Environment

xarray: 2023.3.0

**Comment by pochedls** [comment] 2023-05-08 17:42
This issue might be a duplicate of #451 (if so, maybe one can be closed as a duplicate). I think this deserves more scrutiny, but for now I thought the following would help:

* Note that the underlying issue is that the dataset `lon_bnds` are different across files
* The secondary issue is that xcdat sets `data_vars="minimal"` (which is passed to xarray) so that the bounds do not have a time dimension – this is problematic when the bounds vary by time
* Two options work:
    * `ds = xr.open_mfdataset(filq, data_vars="all")`: This produces a `lon_bnds` array of size [time, lon, bnds] – this leads to issues with `xcdat.spatial.get_weights()` and `xcdat.spatial.average()`
    * `ds = xc.open_mfdataset(filq, drop_variables="lon_bnds")`: This produces a "typical" `lon_bnds` of size [lon, bnds] (but the bounds are generated by xcdat)

**Comment by bonfils2** [comment] 2023-05-09 06:18
Thanks, that is really helpful! For the moment, I adopted ds = xc.open_mfdataset(filq, drop_variables="lon_bnds"), because I need to perform spatial averages. 
I agree that this deserves more scrutiny, and I am happy to close as duplicate of #451. However, you provide here two temporary solutions that I do not see in #451.

**Comment by pochedls** [comment] 2023-05-09 16:24
I think we need to (again) revisit whether to drop `data_vars="minimal"` as the default in `xcdat.open_mfdataset`. Doing so would:

* produce lat/lon bounds with a time dimension, which is annoying, but may be a good thing
* require updates to `get_weights` to produce 3D weights and `spatial_average` to handle the 3D weights

Would there be other consequences? 

See #136 / #143 / #394 / https://github.com/pydata/xarray/issues/438

I think the ideal solution might be something like:

* Keep `data_vars="minimal"` as the default (so that we don't append on `time` to variables that don't need it)
* Catch instances where this is problematic (not sure how) and use the xarray default `data_vars="all"` (with a user warning)
* Update `get_weights` and `spatial_average` to handle cases in which we have 3D bounds

**Comment by chengzhuzhang** [comment] 2023-05-09 22:05
I was curious about the fact that `compact=override` didn't work. It could possibly caused by data problem, where the lon_bnds difference between files are inconsistent and not minor floating point difference. It turned out to be that the conflict happens during the transition around year 1900 (specificly, /p/css03/esgf_publish/CMIP6/CMIP/NCC/NorESM2-LM/piControl/r1i1p1f1/Amon/tas/gn/v20210118/tas_Amon_NorESM2-LM_piControl_r1i1p1f1_gn_189101-190012.nc and tas_Amon_NorESM2-LM_piControl_r1i1p1f1_gn_190101-191012.nc). The bounds values are 1.5 off between two files. (And I don't know the exact reason why compact=override would not resolve this)

for this type of data problem, I think it could be addressed outside of xcdat. And in this particular case, dropping `lon_bnds` seems to be a viable workaround.

**Comment by tomvothecoder** [comment] 2023-05-09 23:05
> I was curious about the fact that compact=override didn't work. It could possibly caused by data problem, where the lon_bnds difference between files are inconsistent and not minor floating point difference. It turned out to be that the conflict happens during the transition around year 1900 (specificly, /p/css03/esgf_publish/CMIP6/CMIP/NCC/NorESM2-LM/piControl/r1i1p1f1/Amon/tas/gn/v20210118/tas_Amon_NorESM2-LM_piControl_r1i1p1f1_gn_189101-190012.nc and tas_Amon_NorESM2-LM_piControl_r1i1p1f1_gn_190101-191012.nc). The bounds values are 1.5 and more off between two files . (And I don't know the exact reason why compact=override would not resolve this)
> 
> for this type of data problem, I think it could be addressed outside of xcdat. And in this particular case, dropping lon_bnds seems to be a viable workaround.

Thanks for investigating @chengzhuzhang. I agree that xCDAT should not handle data quality issues. Even if CDAT might be able to open files in cases where xCDAT cannot, we have found that CDAT is not always doing the right thing under the hood (and it gets hard to debug why).

From what I can tell, xarray and other general-purpose libraries don't handle data quality issues directly because of how nuanced they can be. Instead, they provide options and alternatives for the user to try to work through them manually. I like this approach because the user gets a better understanding of the data they are working with.

It is actually a good thing that xarray catches issues where values aren't consistent across files and yells at the user about it. I wonder what CDAT does in these cases?

**Comment by pochedls** [comment] 2023-05-09 23:38
A couple comments:

* This is probably a dataset issue – but it doesn't have to be. Maybe someone might want their bounds to change over time? This produces an error in `xcdat` but not `xarray` – so maybe we should be able to handle this (weird) case. 
    * If so, we might just need to update `get_weights()` (I'm not sure if spatial averager would need to be changed). 
* I realize that this file can also be opened with: `ds = xc.open_mfdataset(fn, compat='override', coords='minimal')` [Note to @lee1043 & @bonfils2 - another method to open this dataset]. Did the `xarray` logic around this change a little bit (and we should just update our [FAQ](https://xcdat.readthedocs.io/en/stable/faqs.html#how-do-i-open-a-multi-file-dataset-with-values-that-conflict))?

**Comment by chengzhuzhang** [comment] 2023-05-09 23:48
good point, I just tried `xarray` actually handles open these files without an error.. so some more strict checkers are on in xcdat...

**Comment by tomvothecoder** [comment] 2023-05-10 18:47
Closing this issue in favor of #473

**Closed by tomvothecoder** 2023-05-10 18:47 UTC
Labels: Type: Bug, Priority: Medium
