### ISSUE TITLE
[Bug]: xc.swap_lon_axis doesn't work properly for TRMM-3B43v-7_BE_gn precipitation data

### ISSUE THREAD

**Issue by bosup** [xCDAT/xcdat#692] opened 2024-09-05 23:21 UTC
### What happened?

error converting 0-360 longitude coordinate to -180-180 with xc.swap_lon_axis()

[xd_mpi_obs.nc.zip](https://github.com/user-attachments/files/16901053/xd_mpi_obs.nc.zip)

`
import xcdat as xc
from pcmdi_metrics.io import load_regions_specs, da_to_ds

regions_specs = load_regions_specs()
ds = xc.open_dataset("xd_mpi_obs.nc")
ds = xc.swap_lon_axis(ds, to=(-180, 180))

`
TypeError: unsupported operand type(s) for +: 'cftime._cftime.DatetimeNoLeap' and 'int'

### Relevant log output

```python
Traceback (most recent call last):
  File "/home/user/PMP_240131/pcmdi_metrics/pcmdi_metrics/monsoon_wang/debug_regions_specs.py", line 47, in <module>
    ds = xc.swap_lon_axis(ds, to=(-180, 180))
  File "/home/user/miniconda3/envs/PMP_240423/lib/python3.10/site-packages/xcdat/axis.py", line 254, in swap_lon_axis
    new_coord = _swap_lon_axis(ds.coords[key], to)
  File "/home/user/miniconda3/envs/PMP_240423/lib/python3.10/site-packages/xcdat/axis.py", line 370, in _swap_lon_axis
    new_coords = ((coords + 180) % 360) - 180
  File "/home/user/miniconda3/envs/PMP_240423/lib/python3.10/site-packages/xarray/core/_typed_ops.py", line 246, in __add__
    return self._binary_op(other, operator.add)
  File "/home/user/miniconda3/envs/PMP_240423/lib/python3.10/site-packages/xarray/core/dataarray.py", line 4700, in _binary_op
    f(self.variable, other_variable_or_arraylike)
  File "/home/user/miniconda3/envs/PMP_240423/lib/python3.10/site-packages/xarray/core/_typed_ops.py", line 464, in __add__
    return self._binary_op(other, operator.add)
  File "/home/user/miniconda3/envs/PMP_240423/lib/python3.10/site-packages/xarray/core/variable.py", line 2298, in _binary_op
    f(self_data, other_data) if not reflexive else f(other_data, self_data)
TypeError: unsupported operand type(s) for +: 'cftime._cftime.DatetimeNoLeap' and 'int'
```

### Environment

python: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0]
python-bits: 64
OS: Linux
OS-release: 3.10.0-1160.108.1.el7.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
libhdf5: 1.14.0
libnetcdf: 4.9.2

xarray: 2024.3.0
pandas: 2.2.2
numpy: 1.23.5
scipy: 1.13.0
netCDF4: 1.6.3
pydap: None
h5netcdf: None
h5py: None
Nio: None
zarr: None
cftime: 1.6.3
nc_time_axis: 1.4.1
iris: None
bottleneck: None
dask: 2024.4.2
distributed: 2024.4.2
matplotlib: 3.7.1
cartopy: 0.22.0
seaborn: 0.12.2
numbagg: None
fsspec: 2024.3.1
cupy: None
pint: None
sparse: 0.15.1
flox: None
numpy_groupies: None
setuptools: 67.7.2
pip: 23.1.2
conda: None
pytest: 7.3.1
mypy: None
IPython: 8.11.0
sphinx: 5.3.0

**Comment by lee1043** [comment] 2024-09-06 00:09
Reproduce the error with a minimal code:

```python
import xcdat as xc
ds = xc.open_dataset("xd_mpi_obs.nc")
print(ds.lon)
ds = xc.swap_lon_axis(ds, to=(-180, 180))
```

ds.lon:
```
<xarray.DataArray 'lon' (lon: 288)> Size: 2kB
array([  0.  ,   1.25,   2.5 , ..., 356.25, 357.5 , 358.75])
Coordinates:
  * lon      (lon) float64 2kB 0.0 1.25 2.5 3.75 5.0 ... 355.0 356.2 357.5 358.8
    time     object 8B ...
Attributes:
    axis:           X
    bounds:         lon_bnds
    standard_name:  longitude
    title:          Longitude
    type:           double
    units:          degrees_east
    valid_max:      360.0
    valid_min:      0.0
```

Error message:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[9], [line 1](vscode-notebook-cell:?execution_count=9&line=1)
----> [1](vscode-notebook-cell:?execution_count=9&line=1) ds = xc.swap_lon_axis(ds, to=(-180, 180))

File ~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xcdat/axis.py:254, in swap_lon_axis(dataset, to, sort_ascending)
    [252](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xcdat/axis.py:252) # Attempt to swap the orientation for longitude coordinates.
    [253](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xcdat/axis.py:253) for key in coord_keys:
--> [254](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xcdat/axis.py:254)     new_coord = _swap_lon_axis(ds.coords[key], to)
    [256](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xcdat/axis.py:256)     if ds.coords[key].identical(new_coord):
    [257](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xcdat/axis.py:257)         continue

File ~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xcdat/axis.py:370, in _swap_lon_axis(coords, to)
    [366](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xcdat/axis.py:366) with xr.set_options(keep_attrs=True):
    [367](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xcdat/axis.py:367)     if to == (-180, 180):
    [368](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xcdat/axis.py:368)         # FIXME: Performance warning produced after swapping and then sorting
    [369](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xcdat/axis.py:369)         # based on how datasets are chunked.
--> [370](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xcdat/axis.py:370)         new_coords = ((coords + 180) % 360) - 180
    [371](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xcdat/axis.py:371)     elif to == (0, 360):
    [372](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xcdat/axis.py:372)         # Example with 180 coords: [-180, -0, 179] -> [0, 180, 360]
    [373](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xcdat/axis.py:373)         # Example with 360 coords: [60, 150, 360] -> [60, 150, 0]
    [374](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xcdat/axis.py:374)         # FIXME: Performance warning produced after swapping and then sorting
    [375](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xcdat/axis.py:375)         # based on how datasets are chunked.
    [376](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xcdat/axis.py:376)         new_coords = coords % 360

File ~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/_typed_ops.py:246, in DataArrayOpsMixin.__add__(self, other)
    [245](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/_typed_ops.py:245) def __add__(self, other: DaCompatible) -> Self:
--> [246](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/_typed_ops.py:246)     return self._binary_op(other, operator.add)

File ~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/dataarray.py:4700, in DataArray._binary_op(self, other, f, reflexive)
   [4696](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/dataarray.py:4696) other_variable_or_arraylike: DaCompatible = getattr(other, "variable", other)
   [4697](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/dataarray.py:4697) other_coords = getattr(other, "coords", None)
   [4699](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/dataarray.py:4699) variable = (
-> [4700](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/dataarray.py:4700)     f(self.variable, other_variable_or_arraylike)
   [4701](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/dataarray.py:4701)     if not reflexive
   [4702](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/dataarray.py:4702)     else f(other_variable_or_arraylike, self.variable)
   [4703](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/dataarray.py:4703) )
   [4704](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/dataarray.py:4704) coords, indexes = self.coords._merge_raw(other_coords, reflexive)
   [4705](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/dataarray.py:4705) name = self._result_name(other)

File ~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/_typed_ops.py:464, in VariableOpsMixin.__add__(self, other)
    [463](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/_typed_ops.py:463) def __add__(self, other: VarCompatible) -> Self | T_DataArray:
--> [464](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/_typed_ops.py:464)     return self._binary_op(other, operator.add)

File ~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/variable.py:2298, in Variable._binary_op(self, other, f, reflexive)
   [2295](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/variable.py:2295) attrs = self._attrs if keep_attrs else None
   [2296](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/variable.py:2296) with np.errstate(all="ignore"):
   [2297](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/variable.py:2297)     new_data = (
-> [2298](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/variable.py:2298)         f(self_data, other_data) if not reflexive else f(other_data, self_data)
   [2299](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/variable.py:2299)     )
   [2300](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/variable.py:2300) result = Variable(dims, new_data, attrs=attrs)
   [2301](https://file+.vscode-resource.vscode-cdn.net/Users/lee1043/Documents/Research/xcdat/test_lon_swap/~/mambaforge/envs/pmp_devel_20240425/lib/python3.10/site-packages/xarray/core/variable.py:2301) return result

TypeError: unsupported operand type(s) for +: 'cftime._cftime.DatetimeNoLeap' and 'int'
```

**Comment by lee1043** [comment] 2024-09-06 00:16
@bosup it looks like there is a data issue here. Could you please check if this addresses your issue?

`ds` has an empty coordinate time. Once I removed it, no error occurred. 

<img width="908" alt="Screenshot 2024-09-05 at 5 12 45 PM" src="https://github.com/user-attachments/assets/fb66af29-355e-436f-a4e8-cc5e3ca266ea">


```python
import xcdat as xc
ds = xc.open_dataset("xd_mpi_obs.nc")
ds = ds.drop_vars(["time"])
ds = xc.swap_lon_axis(ds, to=(-180, 180))
print(ds.lon)
```

`ds.lon` after swap:
```
<xarray.DataArray 'lon' (lon: 288)> Size: 2kB
array([-180.  , -178.75, -177.5 , ...,  176.25,  177.5 ,  178.75])
Coordinates:
  * lon      (lon) float64 2kB -180.0 -178.8 -177.5 -176.2 ... 176.2 177.5 178.8
Attributes:
    axis:           X
    bounds:         lon_bnds
    standard_name:  longitude
    title:          Longitude
    type:           double
    units:          degrees_east
    valid_max:      360.0
    valid_min:      0.0
```

**Comment by lee1043** [comment] 2024-09-06 00:48
@bosup If your data contains a time series, can you make the sample input to include first 10 time steps or so, so we can see if the same error still occurs?

**Comment by bosup** [comment] 2024-09-06 01:26
> @bosup it looks like there is a data issue here. Could you please check if this addresses your issue?
> 
> `ds` has an empty coordinate time. Once I removed it, no error occurred.
> 
> <img alt="Screenshot 2024-09-05 at 5 12 45 PM" width="908" src="https://private-user-images.githubusercontent.com/17091564/364989308-fb66af29-355e-436f-a4e8-cc5e3ca266ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1ODYxNjIsIm5iZiI6MTcyNTU4NTg2MiwicGF0aCI6Ii8xNzA5MTU2NC8zNjQ5ODkzMDgtZmI2NmFmMjktMzU1ZS00MzZmLWE0ZTgtY2M1ZTNjYTI2NmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDAxMjQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNTllZWE4NDc4ZjVmZjMzYjg1NDlmMWI2ZjEyYjFkMzVjNDM2NzU5NTMzMTcxZDQ2ZWQ0MWMzOWUyZGQ5NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ShSGgxptVok2hg_fkbVLuyeak2DBY5Ws1t_B-dVfakY">
> Added `drop_vars` to remove the empty `time` coordinate:
> 
> ```python
> import xcdat as xc
> ds = xc.open_dataset("xd_mpi_obs.nc")
> ds = ds.drop_vars(["time"])
> ds = xc.swap_lon_axis(ds, to=(-180, 180))
> print(ds.lon)
> ```
> 
> `ds.lon` after swap:
> 
> ```
> <xarray.DataArray 'lon' (lon: 288)> Size: 2kB
> array([-180.  , -178.75, -177.5 , ...,  176.25,  177.5 ,  178.75])
> Coordinates:
>   * lon      (lon) float64 2kB -180.0 -178.8 -177.5 -176.2 ... 176.2 177.5 178.8
> Attributes:
>     axis:           X
>     bounds:         lon_bnds
>     standard_name:  longitude
>     title:          Longitude
>     type:           double
>     units:          degrees_east
>     valid_max:      360.0
>     valid_min:      0.0
> ```

it works now after dropping time dimension. Thanks!

**Comment by bosup** [comment] 2024-09-06 01:28
> @bosup If your data contains a time series, can you make the sample input to include first 10 time steps or so, so we can see if the same error still occurs?

the data doesn't contain a time series. 
suggested change to region_subset() function by adding the following lines:
                    try:
                        ds = ds.drop_vars(["time"])
                    except:
                        pass
                    ds = xc.swap_lon_axis(ds, to=(-180, 180))

**Comment by lee1043** [comment] 2024-09-06 01:29
@bosup Great, thanks for confirming. Is the `pr` always one time step because it is climatology value? 

I am closing this issue, but please feel free to reopen when you still have the issue.

**Closed by lee1043** 2024-09-06 01:29 UTC
Labels: type: bug

**Comment by bosup** [comment] 2024-09-06 22:06
> `pr` always one time step because it is climatology value
Yes it's always one time step
